MyMvcApp/Models/ErrorViewModel.cs
namespace MyMvcApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MyMvcApp/Controllers/AboutController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MyMvcApp.Models;

namespace MyMvcApp.Controllers;

public class AboutController : Controller
{
    
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MyMvcApp/Controllers/ConceptsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MyMvcApp.Models;

namespace MyMvcApp.Controllers;

public class ConceptsController : Controller
{
    
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Details()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MyMvcApp/Controllers/GaleryController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MyMvcApp.Models;

namespace MyMvcApp.Controllers;

public class GaleryController : Controller
{
    
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MyMvcApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MyMvcApp.Models;

namespace MyMvcApp.Controllers;

public class HomeController : Controller
{
   

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MyMvcApp/Views/About/Index.cshtml
<div id="footer">
        <div class="container">
            <div class="row" style="color: aqua;">
                <div class="col" id="mrgn">
                    <h1>Hakkımızda</h1>
                    <div class="ince-hr col-2"></div>
                </div>
                <div class="w-100"></div>
                <div class="col-2" id="mrgn">
                    <p>WinnerOrganizasyon/Hakkımızda</p>
                </div>
            </div>
        </div>

    </div>
    <div id="mid">
        <div class="container">
            <div class="row">
                <div class="col text-dark" style="margin-top: 7%;margin-bottom: 7%;">
                    <h1 id="title"><img src="~/organize/winner.png"  alt="" style="width: 20%;background-color:blueviolet;border-radius: 50%;"></h1>
                </div>
                <div class="w-100"></div>
                <div class="col"><img src="~/organize/resim10.jpg" alt="" style="width:100%;"></div>
                <div class="col">
                    <p style="text-align: start;">Winner Organizasyon, hayatınızın en özel anlarını unutulmaz kılmak için burada! Biz, düğünlerden
                        kınalara, baby shower partilerinden özel hediyeliklere kadar her türlü organizasyonu planlama ve
                        gerçekleştirme konusunda uzmanlaşmış bir ekip olarak sizin yanınızdayız.<br><br><br><br>

                        Müşterilerimizin hayallerini gerçeğe dönüştürmek için yaratıcı fikirlerimiz ve detaylara
                        verdiğimiz özen ile tanınıyoruz. Her etkinliği benzersiz kılmak için özgün konseptler
                        geliştiriyor, her detayı özenle planlayarak en unutulmaz anıları oluşturuyoruz.<br><br><br><br>

                        Winner Organizasyon olarak, müşteri memnuniyetini her şeyin önünde tutuyoruz. Her bir etkinliği,
                        sizin beklentilerinizi aşacak şekilde özel ve kişiselleştirilmiş bir deneyim haline getirmek
                        için çabalıyoruz. Profesyonellik, titizlik ve samimiyetle yaklaşıyor, her müşterimizin özel
                        günlerini benzersiz kılmak için elimizden gelenin en iyisini yapıyoruz.<br><br><br><br>

                        Bizimle çalışarak, her detayı bizimle paylaşın ve hayalinizdeki etkinliği birlikte
                        gerçekleştirelim. Size özel bir deneyim sunmak için buradayız. Bizimle iletişime geçin ve Winner
                        Organizasyon farkını yaşayın!<br><br><br><br>

                        Unutulmaz anılar ve mutlu başlangıçlar için Winner Organizasyon'u tercih edin!</p>
                </div>
            </div>
        </div>
        <div class="kalın-hr"></div>
    </div>

    </div>

MyMvcApp/Views/Communucation/Index.cshtml
 <div id="footer">
        <div class="container">
            <div class="row" style="color: aqua;">
                <div class="col" id="mrgn">
                    <h1>İletişim</h1>
                    <div class="ince-hr col-2"></div>
                </div>
                <div class="w-100"></div>
                <div class="col-3" id="mrgn">
                    <p>WinnerOrganizasyon/İletişim</p>
                </div>
            </div>
        </div>
    </div>
<div class="container" id="mrgn">
    <div class="row">
        <div class="col">
            <div class="col" style="margin-top: 40%;">
                <div class="row"  style="margin-top: 20%;">
                    <div class="col-0"><i class="fa-solid fa-location-dot fa-lg"></i></div>
                    <div class="col-9"><h5 style="text-align: center;">Avcılar, Karahöyük Cd. 46-52, 06210 Yenimahalle/Ankara</h5></div>
                </div>
            </div>
             <div class="row" style="margin-top: 20%;">
            <div class="col"><i class="fa-solid fa-phone fa-lg"></i></div>
                    <div class="col-10"><h5>+90 0552 944 55 06</h5></div>
                </div>
                <div class="row" style="margin-top: 20%;">
            <div class="col"><i class="fa-solid fa-envelope fa-lg"></i></div>
                    <div class="col-11"><h5></h5></div>
                </div>
        </div>
        <div class="col-6">
            <script></script>
            <div>
                <h1 style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif, Times, serif;color: aqua"
                    class="d-flex justify-content-center">
                    Teklif İsteyin
                </h1>
                <div class="ince-hr col-3"></div>
                <div class="d-flex justify-content-center">
                    <div>
                        <form id="borderimage">
                            <div class="row" id="message" style="width:770px;height:460px">
                                <div class="form-group">
                                    <div class="col"> <input type="text" id="exampleInputEmail1"
                                            placeholder="İsminizi giriniz">
                                    </div>
                                </div>
                                <div class="w-100"></div>
                                <div class="form-group">
                                    <div class="col"> <input type="text" id="exampleInputEmail1"
                                            placeholder="Numaranızı giriniz">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col"> <input type="email" id="exampleInputEmail1"
                                            placeholder="E-posta giriniz">
                                    </div>
                                </div>
                                <div class="w-100"></div>
                                <div class="form-group">
                                    <div class="col"><textarea id="message" placeholder="Mesajınızı Yazınız" rows="5"
                                            cols="70%"></textarea></div>
                                </div>
                                <div class="w-100"></div>
                                <div class="form-group">
                                    <input class="btn btn-info" type="submit" value="Gönder">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
<div class="col-12">
    <div id="Location">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3056.9713314994588!2d32.780287784460846!3d39.98674599805784!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14d34bdd8fe0afb7%3A0x6a6df4a9cbc754a1!2sAvc%C4%B1lar%2C%20Karah%C3%B6y%C3%BCk%20Cd.%2046-52%2C%2006210%20Yenimahalle%2FAnkara!5e0!3m2!1str!2str!4v1709049823016!5m2!1str!2str"
            width="100%" height="700" style="border:0;" allowfullscreen="" loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>

MyMvcApp/Views/Concepts/Details.cshtml
 <div id="footer">
        <div class="container">
            <div class="row" style="color: aqua;">
                <div class="col" id="mrgn">
                    <h1>Konseptlerimiz</h1>
                    <div class="ince-hr col-2"></div>
                </div>
                <div class="w-100"></div>
                <div class="col-2" id="mrgn">
                    <p>WinnerOrganizasyon/Konseptlerimiz/Detay</p>
                </div>
            </div>
        </div>
    </div>
    <div id="conceptDetails">
        <div class="container">
            <div class="row d-flex justify-content-start">
                <h1>Kına Konsept</h1>
                <div class="w-100"></div>
                <p style="opacity: 0.4;"> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eum, assumenda?</p>
              <div class="w-100"></div>
              <div class="row d-flex justify-content-start">
                <img src="~/organize/birthday.jpeg" alt="" style="width: 80%;">
            </div>
          </div>
    
    </div>
     <div id="pht" class="slider-container">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1>Fotoğraflar</h1>
                    <div class="col-1 ince-hr"></div><br>
                </div>
                <div class="w-100"></div>
                <div class="col">
                    <img src="~/organize/winner.png" alt="" style="width: 10%;background-color:darkgreen;border-radius: 50%;">
                </div>
                <div class="w-100"></div>
                    <div class="col" style="margin-top: 10%;">
                        <a href="#pht" class="photo-link">
                            <img src="~/organize/birthday.jpeg" alt="" class="photo">
                        </a>
                    </div>
                    <div class="col" style="margin-top: 10%;">
                        <a href="#pht" class="photo-link">
                            <img src="~/organize/back.jpeg" alt="" class="photo">
                        </a>
                    </div>
                    <div class="col" style="margin-top: 10%;">
                        <a href="#pht" class="photo-link">
                            <img src="~/organize/birthday.jpeg" alt="" class="photo">
                        </a>
                    </div>
                    
                    <!-- Additional photos here -->
                </div>
            </div>
    
    </div>

MyMvcApp/Views/Concepts/Index.cshtml
 <div id="footer">
        <div class="container">
            <div class="row" style="color: aqua;">
                <div class="col" id="mrgn">
                    <h1>Konseptlerimiz</h1>
                    <div class="ince-hr col-2"></div>
                </div>
                <div class="w-100"></div>
                <div class="col-2" id="mrgn">
                    <p>WinnerOrganizasyon/Konseptlerimiz</p>
                </div>
            </div>
        </div>
    </div>
    <div id="concept">
        <div class="row">
            <div class="col">
                <a asp-controller="Concepts" asp-action="Details" class="bck"><img src="~/organize/birthday.jpeg" alt="">
                    <div class="w-100"></div>
                    <h5>Labirent Konsept</h5>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, iste?</p>

                </a>
            </div>
            <div class="col">
                <a asp-controller="Concepts" asp-action="Details" class="bck"><img src="~/organize/birthday.jpeg" alt="">
                    <div class="w-100"></div>
                    <h5>Perde Konsept</h5>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, iste?</p>

                </a>
            </div>
            <div class="col">
                <a asp-controller="Concepts" asp-action="Details" class="bck"><img src="~/organize/birthday.jpeg" alt="">
                    <div class="w-100"></div>
                    <h5>Zerafet Konsept</h5>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, iste?</p>

                </a>
            </div>
            <div class="w-100"></div>
            <div class="col" class="bck">
                <a asp-controller="Concepts" asp-action="Details" ><img src="~/organize/birthday.jpeg" alt="">
                    <div class="w-100"></div>
                    <h5>Kına Konsept</h5>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, iste?</p>

                </a>
            </div>
            <div class="col" class="bck">
                <a asp-controller="Concepts" asp-action="Details" class="bck"><img src="~/organize/birthday.jpeg" alt="">
                    <div class="w-100"></div>
                    <h5>Kapı Konsept</h5>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, iste?</p>
                </a>
            </div>
            <div class="col">
                <a asp-controller="Concepts" asp-action="Details"  class="bck"><img src="~/organize/birthday.jpeg" alt="">
                    <div class="w-100"></div>
                    <h5>Çiçek Duvar Konsept</h5>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, iste?</p>
                </a>
            </div>
        </div>
    </div>

MyMvcApp/Views/Galery/Index.cshtml
<div id="footer">
    <div class="container">
        <div class="row" style="color: aqua;">
            <div class="col" id="mrgn">
                <h1>Galeri</h1>
                <div class="ince-hr col-2"></div>
            </div>
            <div class="w-100"></div>
            <div class="col-2" id="mrgn">
                <p>WinnerOrganizasyon/Galeri</p>
            </div>
        </div>
    </div>
</div>
<div id="pht" class="slider-container" style="margin-bottom: 20%;">
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Galeri</h1>
                <div class="col-1 ince-hr"></div><br>
            </div>

            <div class="w-100"></div>
            <div class="col">
                <img src="~/organize/winner.png" alt=""
                    style="width: 10%;background-color:darkgreen;border-radius: 50%;">
            </div>
            <div class="row" style="margin-top: 10%;">
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim6.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim7.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim9.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim8.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="w-100" style="margin-top: 10%;"></div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim8.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim5.jpg" alt="Error"
                                class="photo "></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim8.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim8.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                 <div class="w-100" style="margin-top: 10%;"></div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim4.jpeg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim3.jpeg" alt="Error"
                                class="photo "></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim2.jpeg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim1.jpeg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                 <div class="w-100" style="margin-top: 10%;"></div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim10.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim11.jpg" alt="Error"
                                class="photo "></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim12.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim13.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="w-100" style="margin-top: 10%;"></div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim5.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim6.jpg" alt="Error"
                                class="photo "></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim7.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim8.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                 <div class="w-100" style="margin-top: 10%;"></div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim5.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim16.jpg" alt="Error"
                                class="photo "></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim14.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
                <div class="col">
                    <div><a href="#pht" class="photo-link"><img src="~/organize/resim15.jpg" alt="Error"
                                class="photo"></a>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

MyMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

    <title>Winner Organizasyon - Düğün ve Nişan Organizasyon Ankara</title>
    <link rel="icon" type="image/x-icon" href="~/organize/image.jpg">
    <meta name="description"
        content="Ankara nişan organizasyonu, hastane odası süsleme ve doğum günü organizasyonunda kusursuz hizmetin adresi.Winner Organizasyon, düğün, kına gecesi ve baby shower gibi özel etkinlikler için profesyonel organizasyon hizmetleri sunmaktadır.Class Organizasyon Ankara Organizasyon ve Kiralama Hizmetleri. Düğün, Nişan, Kına Gecesi, Sünnet, Mezuniyet Gecesi organizasyonları. Sandalye ve masa kiralama.">
    <meta name="keywords"
        content="Hastane odası süslemesi, Doğum odası süslemesi, Nişan organizasyonu, söz organizasyonu, Ankara organizasyon, baby shower partisi, gender parti organizasyonu, Ankara açılış davet organizasyonu, mezuniyet partisi,">
    <meta name="author" content="Winner Organizasyon,Ankara Organizasyon">

</head>

<body style="overflow-y: auto;">

    <nav class="navbar navbar-expand-lg navbar-light bg-dark" style="height: 7em;">

        <a class="navbar-brand text-white" href="/"><img src="~/organize/winner.png" alt="" style="width: 30%;"
                class="ml-5"></a>

       
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav ml-auto mt-5 mt-lg-0 mx-5">
                <li class="nav-item active awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="Home">
                        <p id="text-nav">Ana Sayfa</p> <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="About">
                        <p id="text-nav">Hakkımızda</p>
                    </a>
                </li>
                <li class="nav-item awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="Concepts">
                        <p id="text-nav">Konseptlerimiz</p>
                    </a>
                </li>
                <li class="nav-item awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="Galery">
                        <p id="text-nav">Galeri</p>
                    </a>
                </li>
                <li class="nav-item awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="Communucation">
                        <p id="text-nav">İletişim</p>
                    </a>
                </li>
            </ul>
        </div>


    </nav>
<div >
 <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" aria-controls="navbarTogglerDemo02"
            data-target="#navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
 </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav ml-auto mt-5 mt-lg-0 mx-5">
                <li class="nav-item active awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="Home">
                        <p id="text-nav">Ana Sayfa</p> <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="About">
                        <p id="text-nav">Hakkımızda</p>
                    </a>
                </li>
                <li class="nav-item awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="Concepts">
                        <p id="text-nav">Konseptlerimiz</p>
                    </a>
                </li>
                <li class="nav-item awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="Galery">
                        <p id="text-nav">Galeri</p>
                    </a>
                </li>
                <li class="nav-item awayer">
                    <a class="nav-link text-white" asp-action="Index" asp-controller="Communucation">
                        <p id="text-nav">İletişim</p>
                    </a>
                </li>
            </ul>
        </div>

</div>

    <div>@RenderBody()</div>




    <div style="margin-bottom: 0%;margin-top:20%; height: 7em;background-color: wheat;position: relative; bottom: 0px;">

        <div class="d-flex flex-row mx-5 my-lg-3">
            <div id="design" class="my-4">
                <p id="lastp" style="color:blue;">Design By <i style="color: blueviolet;"> <a
                            href="https://www.instagram.com/burhancvdroglu/" target="_blank"
                            style="outline: none;color: blueviolet;"><b>Burhan Çavdaroğlu</b></a></i></p>
            </div>
            @{
                string text = "@2023 Winner Organizasyon Tüm Hakları Saklıdır";
            }
            <div class="ml-auto my-4 text-dark "><b id="text_">@text</b< /div>
                    <div class="ml-5 my-4 "><a href="https://www.instagram.com/winner.organizasyon/" target="_blank"><i
                                class="fa-brands fa-instagram fa-lg" id="icon"></i></a></div>
                    <div class="ml-2 my-4 "><a href="https://wa.me/05529445506" target="_blank"><i
                                class="fa-brands fa-whatsapp fa-lg" id="icon"></i></a></div>
            </div>
        </div>
        <div class="cornerItem">
            <div class="container">
                <div class="row">
                    <div class="col-0">
                        <div><a href="https://www.instagram.com/winner.organizasyon/" target="_blank"><img
                                    src="~/organize/insta.png" alt="" style="width:80%;"></a></div>
                    </div>
                    <div class="col-0">
                        <div><a href="https://wa.me/05529445506" target="_blank"><img src="~/organize/wp.png" alt=""
                                    style="width:75%;"></a></div>
                    </div>
                </div>

            </div>
            <script src="~/js/site.js"></script>
</body>

</html>